language: erlang

env:
   - ST=Pharo-1.4
   - ST=Pharo-2.0
   - ST=Pharo-3.0
   - ST=GemStone-2.4.5.2
   - ST=GemStone-3.1.0.6
   - ST=GemStone-3.0.1
   - ST=GemStone-3.2.2

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f662b9bc952d22a2f11f
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -q -O builderCI.zip https://github.com/dalehenrich/builderCI/zipball/master
   - unzip -q builderCI.zip
   - cd dalehenrich-builderCI*
   - source build_env_vars
   - ln -s $PROJECT_HOME $GIT_PATH
   - ./build_image.sh

script: $BUILDER_CI_HOME/testTravisCI.sh -verbose
